# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LuckyOne' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RealmSwift'
pod 'Alamofire', '~> 5.2'
pod 'Swinject'

  # Pods for LuckyOne

  target 'LuckyOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
